server:
  port: 10518
spring:
  application:
    name: springboot-thymeleaf
  #thymeleaf
  thymeleaf:
    prefix: classpath:/templates/    #prefix：指定模板所在的目录
    check-template-location: true    #check-tempate-location: 检查模板路径是否存在
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML5    # 用非严格的 HTML
    cache: false    #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。