server:
  port: 10532
spring:
  application:
    name: springboot-rabbitmq
  rabbitmq:
    host: 127.0.0.1
    username: admin
    password: admin
    virtual-host: /
    port: 5672
    listener:
      simple:
        concurrency: 10
        max-concurrency: 20
        prefetch: 50
